---
spring:
  profiles: EurekaServer1

server:
  port: 8761

eureka:
  instance:                       #此Eureka服务实例
    hostname: localhost
  client:                         #此Eureka服务作为客户端的配置
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8762/eureka/
  server:                         #此Eureka服务作为服务端的配置
    eviction-interval-timer-in-ms: 5000
    enable-self-preservation: false

---
spring:
  profiles: EurekaServer2

server:
  port: 8762

eureka:
  instance:                       #此Eureka服务实例
    hostname: localhost
  client:                         #此Eureka服务作为客户端的配置
    register-with-eureka: false           #不注册到defaultZone指定的Eureka服务器（这里指自己）
    fetch-registry: false                 #
    service-url:
      defaultZone: http://localhost:8761/eureka/
  server:                         #此Eureka服务作为服务端的配置
    eviction-interval-timer-in-ms: 5000
    enable-self-preservation: false