server:
  port: 9000

spring:
  application:
    name: msa-test

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
MSA-CRONTAB:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule  #修改某微服务多个应用实例负载均衡策略（默认为轮训 RoundRobinRule）
